sudo: required
services:
  - docker

before_install:
  - docker build -t theuncleshege/docker-react -f Dockerfile.dev .

script:
  - docker run theuncleshege/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-596870276118"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id:
    secure: "$AWS_SECRET_KEY"